/**
 * NODE API : Core/Type/StatusCodes
 * ----------------------------------------------------------------------
 * Uma lista com códigos de status HTTP e nomes dos mesmos.
 * 
 * @author    Fabio Y. Goto <lab@yuiti.com.br>
 * @since     0.0.1
 */
export default {
  100: "Continuar",
  101: "Mudando Protocolos",
  102: "Processamento",
  103: "Dicas Antecipadas",
  200: "OK",
  201: "Criado",
  202: "Aceito",
  203: "Informações Não Autorizadas",
  204: "Nenhum Conteúdo",
  205: "Conteúdo Apagado",
  206: "Conteúdo Parcial",
  207: "Status Múltiplo",
  208: "Já Reportado",
  226: "Manipulação de Instância foi Utilizada (IM Used)",
  300: "Múltipla Escolha",
  301: "Movido Permanentemente",
  302: "Encontrado",
  303: "Veja Outros",
  304: "Não Modificado",
  305: "Use o Proxy",
  306: "Proxy Switch",
  307: "Redirecionamento Temporário",
  308: "Redirecionamento",
  400: "Solicitação Inválida",
  401: "Não Autorizado",
  402: "Pagamento Obrigatório",
  403: "Proibido",
  404: "Não Encontrado",
  405: "Método Não Permitido",
  406: "Não Aceitável",
  407: "Autenticação de Proxy Necessária",
  408: "Tempo Limite de Solicitação",
  409: "Conflito",
  410: "Abandonado",
  411: "Tamanho Obrigatório",
  412: "Falha na Pré-Condição",
  413: "Entidade de Solicitação Muito Grande",
  414: "URI de Solicitação Muito Grande",
  415: "Tipo de Mídia Não Compatível",
  416: "Intervalo de Solicitação Não Atendido",
  417: "Falha na Expectativa",
  418: "Eu Sou Um Bule de Chá",
  422: "Entidade Não Processável",
  423: "Bloqueado",
  424: "Falha na Dependência",
  425: "Coleção Não Ordenada",
  426: "Upgrade Obrigatório",
  428: "Pré-Condição Obrigatória",
  429: "Muitos Requests Realizados",
  431: "Campos do Cabeçalho de Requisição Grandes Demais",
  451: "Não Disponível por Motivos Legais",
  500: "Erro Interno do Servidor",
  501: "Não Implementado",
  502: "Gateway Inválido",
  503: "Serviço Indisponível",
  504: "Tempo Limite de Gateway",
  505: "Versão do HTTP Não Compatível",
  506: "Variante Também Negocia",
  507: "Armazenamento Insuficiente",
  509: "Limite de Banda Excedido",
  510: "Não Estendido"
};
